version: "3.7"
services:
  frontend:
    build: ../../1/frontend-example-docker
    environment:
      - API_URL=http://localhost/api/
    depends_on:
      - backend

  backend:
    build: ../../1/backend-example-docker
    environment:
      - FRONT_URL=http://localhost
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=sasu
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=sasu
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
