version: "3.7"
services:
  frontend:
    build: ../1/frontend-example-docker
    ports:
      - "5000:5000"
  backend:
    build: ../1/backend-example-docker
    ports:
      - "8000:8000"
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis
