version: "3.7"
services:
  frontend:
    build: ../1/frontend-example-docker
    ports:
      - "5000:5000"
  backend:
    build: ../1/backend-example-docker
    ports:
      - "8000:8000"
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=sasu
      - DB_HOST=postgres
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=sasu
